# Generated by Django 6.0 on 2025-12-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0002_remove_leaverequest_user_id_leaverequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfhrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'date')},
        ),
    ]
