# Generated by Django 6.0 on 2026-01-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0004_user_manager_user_role_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lastlogin',
        ),
    ]
