# Generated by Django 6.0 on 2026-01-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0005_remove_user_lastlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
