# Generated by Django 6.0 on 2026-01-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0006_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastlogin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
