# Generated by Django 6.0 on 2026-01-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0007_user_lastlogin_alter_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='employee', max_length=30),
        ),
    ]
