# Generated by Django 6.0 on 2026-01-12 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzz', '0008_rolechoices_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWorkingRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('working_days', models.JSONField()),
                ('daily_work_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weekly_work_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_work_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('FIXED', 'Fixed Holiday'), ('COMP_OFF', 'Complementary Off')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HolidayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('override_type', models.CharField(choices=[('CANCELLED', 'Holiday Cancelled'), ('WORKING_DAY', 'Converted to Working Day'), ('COMP_OFF', 'Complementary Off')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'override_type')},
            },
        ),
    ]
